name: mapsindoors
description: A MapsIndoors flutter plugin
version: 1.0.2
repository: https://github.com/MapsPeople/MapsIndoors-sdk-flutter
homepage: https://www.mapsindoors.com/
documentation: https://app.mapsindoors.com/mapsindoors/reference/flutter/1.0.0/index.html

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: mapsindoors_android
      ios:
        default_package: mapsindoors_ios

dependencies:
  flutter:
    sdk: flutter
  mapsindoors_android: ^1.0.1
  mapsindoors_ios: ^1.0.1
  mapsindoors_platform_interface: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0